package-lock.json
src/components/layout/MenuBar/MenuBar.js
src/components/layout/MenuBar/MenuBar.module.scss

wyszukiwanie na tabletach  jest pod menu, a na mniejszych ekranach jest wyszukiwanie i obok niego ikona mobilnego menu, które po rozwinięciu pokazyuje dropdown.

improved rwd and add dropdown WDP210901-14

---

src/components/common/Swipeable/Swipeable.js
src/components/common/Swipeable/Swipeable.test.js
src/components/features/NewFurniture/NewFurniture.js

Added swipeable function in NewFurniture

WDP210901-13 Add swipeable

---

src/components/layout/CompanyClaim/CompanyClaim.js
src/components/layout/CompanyClaim/CompanyClaimContainer.js
src/components/layout/Header/Header.js

Obok widgetu koszyka w headerze pojawia się ilość produktów pobrana ze stanu aplikacji.

WDP210901-58 - Widget koszyka w headerze

---

src/components/common/ProductBox/ProductBoxContainer.js
src/components/common/PromotedProductBox/PromotedProductBox.js
src/components/common/PromotedProductBox/PromotedProductBox.module.scss
src/components/features/NewFurniture/NewFurniture.js
src/components/features/NewFurniture/NewFurniture.module.scss
src/components/features/ProductCompare/ProductCompareContainer.js
src/components/layout/CompanyClaim/CompanyClaim.js
src/components/layout/CompanyClaim/CompanyClaim.module.scss
src/components/layout/Footer/Footer.js
src/components/layout/Footer/Footer.module.scss
src/components/layout/MenuBar/MenuBar.js
src/components/layout/MenuBar/MenuBar.module.scss
src/components/layout/Promoted/Promoted.js
src/components/layout/Promoted/Promoted.module.scss
src/components/layout/TopBar/TopBar.js
src/components/layout/TopBar/TopBar.module.scss
src/redux/productsRedux.js
src/styles/settings.scss

WDP210901-64 naprawienie błędów w konsoli

WDP210901-64

---

src/App.js
src/components/common/Button/Button.module.scss
src/components/layout/TopBar/TopBar.js
src/components/views/Homepage/Homepage.js
src/components/views/Register/Register.js
src/components/views/Register/Register.module.scss

Task dotyczył przygotowania widoku podstrony Register. Oprócz strony wizualnej, należało zadbać, aby przy zatwierdzaniu, lub rezygnacji klient przechodził na stronę główną.

Task wdp210901 45 1

---

src/components/common/ProductBox/ProductBox.js
src/components/features/ProductRating/ProductRating.js
src/redux/initialState.js
src/redux/productsRedux.js

Dodano funkcjonalność zapisywania ilości ocenionych gwiazdek w localStorage, strona po odświeżeniu zachowuje swoje oceny.
Dodano również możliwość usunięcia swojej oceny poprzez ponownie wybranie tej samej ilości gwiazdek

Wdp210901-50

---

src/components/views/ProductList/ProductList.js

W chwili obecnej sekcja Brands znajduje się tylko na stronie głównej. Zadaniem jest wrzucenie sekcji Brands na sam dół podstrony shop, tuż nad stopką.

Add component Brands to Shop page

---

src/components/common/Button/Button.module.scss
src/components/features/BrandsBox/BrandsBox.module.scss
src/components/layout/Brands/Brands.js
src/components/layout/Brands/Brands.module.scss
src/styles/settings.scss

Zadaniem jest stworzenie wersji mobilnych sekcji "Brands". Klient nie ma designów RWD, więc trzeba zrobić na własną rękę. 
W sliderze ma być tyle elementów, ile zmieści się w całości na danej szerokości ekranu.
Ma działać przesuwanie slajdów za pomocą komponentu Swipeable (jest na niego osobne zadanie – jeśli nie jest gotowe to trzeba przygotować funkcje, które będą wykonywane przy swipe w lewo i w prawo).

Wdp210901-32

---

src/components/common/ProductBox/ProductBox.js
src/components/common/PromotedProductBox/PromotedProductBox.js
src/components/views/Cart/Cart.js
src/components/views/Cart/CartContainer.js
src/redux/cartRedux.js

1. Total przy każdym produkcie, to jego cena razy ilość.
2. Ilość może być zmieniana za pomocą przycisków + i -.
3. Łączna wartość total wszystkich produktów wyświetlana jest w subtotal w karcie Cart Totals.
4.Total w Cart Totals wyświetla łączną cenę z subtotal plus 20$ za przesyłkę.
5. Przycisk krzyżyka przy każdym produkcie wyrzuca produkt z koszyka.

WDP210901-57 Dodanie funkcjonalności koszyka

---

src/components/views/Login/Login.js
src/components/views/Login/Login.module.scss
src/styles/settings.scss

W tym zadaniu należało dodać walidację hasła i e-maila. Przy czym, utrudnieniem było to, że komunikat powinien się pojawiać w kolorze czerwonym, w określonym miejscu formularza Login (zatem nie można było wykorzystać window.alert, które bardzo trudno jest ostylować).
Zgodnie z założeniem hasłem może być tylko pass, natomiast email to admin.

Add alert for wrong email or password

---

src/components/common/ProductBox/ProductBox.js
src/components/layout/CompanyClaim/CompanyClaim.js
src/components/layout/CompanyClaim/CompanyClaim.module.scss
src/components/layout/Footer/Footer.module.scss
src/components/layout/MenuBar/MenuBar.js
src/components/layout/TopBar/TopBar.js
src/components/layout/TopBar/TopBar.module.scss
src/components/views/Cart/Cart.js
src/components/views/Cart/Cart.module.scss
src/components/views/Register/Register.js
src/components/views/Register/Register.module.scss

Wspólny branch dla tasków: 46, 65-2, 67 oraz 69. Przy okazji została wprowadzona mała poprawka w związku z błędami, jakie zaczęły się pojawiać po mergu taska 35 - przy życzliwym wsparciu Roberta :).

Wdp210901 75

---

src/components/common/LastPost/LastPost.js
src/components/common/LastPost/LastPost.module.scss
src/components/features/LatestBlog/LatestBlog.js
src/components/features/LatestBlog/LatestBlog.module.scss
src/components/features/LatestBlog/LatestBlogContainer.js
src/components/views/Homepage/Homepage.js
src/redux/initialState.js
src/redux/postsRedux.js
src/styles/settings.scss

Zadanie polegało na przywróceniu działalności komponentów latestBlog oraz lastPost i ponownych ich ostylowaniu.

Fix Blog issues

---

src/components/layout/BlogArchive/BlogArchive.js
src/components/layout/BlogArchive/BlogArchive.module.scss

Zadanie polegało na dodaniu RWD do podstrony bloga. Zadanie było o tyle trudniejsze, ponieważ początkowy wygląd podstrony się zepsuł (nachodzące na siebie sekcje), więc oprócz utworzenia samych styli RWD musiałem na początek odbudować prawidłowe wyświetlanie strony.

Add RWD for BlogArchive

---

src/App.js
src/components/features/ProductSearch/ProductSearch.js

1. Po kliknięciu w lupkę przy inpucie `search product` zostajesz przeniesiony na nową podstronę wyszukiwania.
2. Wpisana w pole wyszukiwania fraza ma pojawić się w linku, gdzie spacje zastąpione są przez tzw. podłogi, czyli: `_`

Wdp210901 83

---

src/components/features/ProductSlider/ProductSlider.js
src/components/features/ProductSlider/ProductSlider.module.scss
src/components/layout/Gallery/Gallery.js
src/components/layout/Gallery/Gallery.module.scss

Zadaniem jest stworzenie wersji mobilnych sekcji "Galeria". Klient nie ma designów RWD, więc trzeba zrobić na własną rękę. 
Na telefonach pokazujemy tylko taby ze sliderem (na 100% szerokości containera), a ukrywamy duże zdjęcie z prawej. 
W sliderze miniaturek ma być tyle elementów, ile zmieści się w całości na danej szerokości ekranu. Slider miniaturek powinno dać się przewijać również za pomocą komponentu Swipeable (jest na niego osobne zadanie – jeśli nie jest gotowe to trzeba przygotować funkcje, które będą wykonywane przy swipe w lewo i w prawo).

Wdp210901-29

---

src/components/features/FilterByCategories/FilterByCategories.js
src/components/features/FilterByCategories/FilterByCategories.module.scss
src/components/views/ProductList/ProductList.js
src/components/views/ProductList/ProductList.module.scss

W tym zadaniu należało stworzyć widok dla filtrów w oparciu o kategorie mebli. Task nie dotyczył funkcjonalności oraz RWD.

Add filter by categories

---

src/components/features/FilterByColor/FilterByColor.js
src/components/features/FilterByColor/FilterByColor.module.scss
src/components/views/ProductList/ProductList.js
src/components/views/ProductList/ProductList.module.scss

Zadanie dotyczyło przygotowania filtrów w oparciu o kolory bez funkcjonalności oraz RWD.

Wdp210901 62

---

src/components/features/FilterByPrice/FilterByPrice.js
src/components/features/FilterByPrice/FilterByPrice.module.scss
src/components/views/ProductList/ProductList.js
src/components/views/ProductList/ProductList.module.scss

Widok filtrów w odniesieniu do ceny.

Wdp210901 61

---

src/components/views/ProductPage/ProductPage.js

Rearranging the order so that the `product overview` appears first, followed by the `products` in that category.

WDP210901-49: reordering

---

src/components/layout/CompanyClaim/CompanyClaim.js

The client wants the application to take us to the home page after clicking on the project logo.

WDP210901-89: Link logo to homepage

---

src/components/common/ProductBox/ProductBox.js
src/components/layout/Deals/Deals.js
src/components/layout/Deals/Deals.module.scss

Dostosuj sekcję deals, by odpowiednio pokazywała się we wszystkich szerokościach ekranu

Wdp210901-85

---

package.json
src/components/features/NewFurniture/NewFurniture.js
src/components/features/NewFurniture/NewFurniture.module.scss
src/components/features/ProductSearch/ProductSearch.js
src/components/features/ProductSearch/ProductSearchContainer.js
src/components/views/Search/Search.js
src/components/views/Search/SearchContainer.js
src/redux/categoriesRedux.js
src/redux/filtersRedux.js
src/redux/initialState.js
src/redux/store.js

Dodano opcję search, wyświetla produkty odpowiadające wyszukiwanej frazie

WDP210901-90

---

src/components/common/FeatureBox/FeatureBox.js
src/components/common/LastPost/LastPost.js
src/components/common/PromotedProductBox/PromotedProductBox.js
src/components/features/ChatBot/ChatBot.module.scss
src/components/features/CountComments/CountComments.js
src/components/features/ProductRating/ProductRating.js
src/components/features/ProductSlider/ProductSlider.js
src/components/features/SizeFilter/SizeFilter.js
src/components/layout/BlogArchive/BlogArchive.js
src/components/layout/MenuBar/MenuBar.module.scss
src/components/views/Login/Login.js
src/components/views/Login/Login.module.scss
src/redux/initialState.js

Naprawiona większość błędów konsolowych, dwa wynikają z budowy komponentu, aby je usunąć trzeba by go przebudować.

WDP210901-92
